name: Make the PDF report

# This workflow will produce the PDF report using the latest commit of the
# master branch, after having installed the package with pip.

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ['3.9']
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install the package from the git repo
        run: pip install ./

      - name: Make the PDF report
        run: python scripts/outputs/make_pdf_report.py