# For more information see:
# https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Custom python package

on:
  push:
    branches: [ disabled ] # Change back to 'master' to activate this workflow
  pull_request:
    branches: [ disabled ] # Change back to 'master' to activate this workflow

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install pip and flake8
      run: |
        python -m pip install --upgrade pip
        pip install flake8
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
    - name: Install the package
      run: |
        pip install .
    - name: Import the package
      run: |
        python -c "import waste_flow; print(waste_flow.__version__)"
